// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVzKJqs1x1-NA-NyUt6-F38t_CVNxudQ',
    appId: '1:794918109264:web:2d44846364ce0ca240d155',
    messagingSenderId: '794918109264',
    projectId: 'velaris-5a288',
    authDomain: 'velaris-5a288.firebaseapp.com',
    storageBucket: 'velaris-5a288.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh9ylEJ_gApX3xC49hBuM1Af_r2LKTzy0',
    appId: '1:794918109264:android:77e4ea7b9284975b40d155',
    messagingSenderId: '794918109264',
    projectId: 'velaris-5a288',
    storageBucket: 'velaris-5a288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3G5ktu1i0aAmO4EFFaTksYFm4AAPUwOk',
    appId: '1:794918109264:ios:64dfe1ee30cfe88e40d155',
    messagingSenderId: '794918109264',
    projectId: 'velaris-5a288',
    storageBucket: 'velaris-5a288.firebasestorage.app',
    iosClientId: '794918109264-aht4jg8su5akorenur5fr0i90ompjk68.apps.googleusercontent.com',
    iosBundleId: 'com.example.velaris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3G5ktu1i0aAmO4EFFaTksYFm4AAPUwOk',
    appId: '1:794918109264:ios:64dfe1ee30cfe88e40d155',
    messagingSenderId: '794918109264',
    projectId: 'velaris-5a288',
    storageBucket: 'velaris-5a288.firebasestorage.app',
    iosClientId: '794918109264-aht4jg8su5akorenur5fr0i90ompjk68.apps.googleusercontent.com',
    iosBundleId: 'com.example.velaris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZVzKJqs1x1-NA-NyUt6-F38t_CVNxudQ',
    appId: '1:794918109264:web:863056d09120fa9440d155',
    messagingSenderId: '794918109264',
    projectId: 'velaris-5a288',
    authDomain: 'velaris-5a288.firebaseapp.com',
    storageBucket: 'velaris-5a288.firebasestorage.app',
  );
}
